language: ruby
sudo: false
addons:
  apt:
    packages:
    - ruby-dev
    - libffi-dev
    - libgmp-dev
cache: bundler
rvm:
  - 1.9.3
  - 2.1.1
  - 2.2.2
  - ruby-head
before_install:
  - gem update bundler
script: bundle exec rspec
